version: "3.8"

services:
  db:
    image: mysql:8
    restart: unless-stopped
    env_file:
      - "./devcontainer.env"
    environment:
      cap_add: "SYS_NICE"
    ports:
      - "3306:3306"
    volumes:
      - "./config/mysql.cnf:/etc/mysql/conf.d/zmysql.cnf"
      - database:/var/lib/mysql
      # - "../dump/init.sql:/docker-entrypoint-initdb.d/mydb.sql"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  app:
#     image: alchatti/drupal-devcontainer:8.1
    image: mcr.microsoft.com/devcontainers/php:8.1
    env_file:
      - "./devcontainer.env"
    volumes:
      # - "pnpm-store:/home/vscode/.pnpm-store"
#       - "~/.acquia:/home/vscode/.acquia" # Acquia Cloud Cli Share with host
#       - "~/.ssh:/home/vscode/.ssh" # SSH Keys share with host
      - "./config/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf"
#       - "../.dev:/var/www/site-dev"
      - "..:/var/www/html"
    command: sleep infinity
    depends_on:
      - db
volumes:
  database:
  # acquia:
  # create >  docker volume create pnpm-store
  # pnpm-store:
  #   external: true
